using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace APISoftlandAnclaflex.Entities
{
    public partial class Fcrmvi
    {
        public string Fcrmvi_Codemp { get; set; }
        public string Fcrmvi_Modfor { get; set; }
        public string Fcrmvi_Codfor { get; set; }
        public int Fcrmvi_Nrofor { get; set; }
        public int Fcrmvi_Nroitm { get; set; }
        public string Fcrmvi_Nivexp { get; set; }
        public string Fcrmvi_Empapl { get; set; }
        public string Fcrmvi_Modapl { get; set; }
        public string Fcrmvi_Codapl { get; set; }
        public int Fcrmvi_Nroapl { get; set; }
        public int Fcrmvi_Itmapl { get; set; }
        public string Fcrmvi_Expapl { get; set; }
        public string Fcrmvi_Tippro { get; set; }
        public string Fcrmvi_Artcod { get; set; }
        public string Fcrmvi_Modcpt { get; set; }
        public string Fcrmvi_Tipcpt { get; set; }
        public string Fcrmvi_Codcpt { get; set; }
        public string Fcrmvi_Tipori { get; set; }
        public string Fcrmvi_Artori { get; set; }
        public string Fcrmvi_Nserie { get; set; }
        public string Fcrmvi_Ndespa { get; set; }
        public string Fcrmvi_Envase { get; set; }
        public string Fcrmvi_Notros { get; set; }
        public string Fcrmvi_Natrib { get; set; }
        public string Fcrmvi_Nestan { get; set; }
        public string Fcrmvi_Nubica { get; set; }
        public string Fcrmvi_Nfecha { get; set; }
        public string Fcrmvi_Tserie { get; set; }
        public string Fcrmvi_Tdespa { get; set; }
        public string Fcrmvi_Tenvas { get; set; }
        public string Fcrmvi_Totros { get; set; }
        public string Fcrmvi_Tatrib { get; set; }
        public string Fcrmvi_Testan { get; set; }
        public string Fcrmvi_Tubica { get; set; }
        public string Fcrmvi_Tfecha { get; set; }
        public string Fcrmvi_Deposi { get; set; }
        public string Fcrmvi_Sector { get; set; }
        public string Fcrmvi_Sucurs { get; set; }
        public string Fcrmvi_Nrocta { get; set; }
        public string Fcrmvi_Nrosub { get; set; }
        public decimal? Fcrmvi_Oldpre { get; set; }
        public decimal? Fcrmvi_Newpre { get; set; }
        public decimal? Fcrmvi_Precio { get; set; }
        public decimal? Fcrmvi_Cantid { get; set; }
        public decimal? Fcrmvi_Facsec { get; set; }
        public decimal? Fcrmvi_Cntsec { get; set; }
        public string Fcrmvi_Unimed { get; set; }
        public string Fcrmvi_Unisec { get; set; }
        public string Fcrmvi_Tipuni { get; set; }
        public string Fcrmvi_Unifac { get; set; }
        public decimal? Fcrmvi_Facfac { get; set; }
        public decimal? Fcrmvi_Cntfac { get; set; }
        public string Fcrmvi_Unialt { get; set; }
        public decimal? Fcrmvi_Facalt { get; set; }
        public decimal? Fcrmvi_Cntalt { get; set; }
        public string Fcrmvi_Unicon { get; set; }
        public decimal? Fcrmvi_Faccon { get; set; }
        public decimal? Fcrmvi_Cntcon { get; set; }
        public DateTime? Fcrmvi_Fchent { get; set; }
        public DateTime? Fcrmvi_Fchhas { get; set; }
        public decimal? Fcrmvi_Pctbf1 { get; set; }
        public decimal? Fcrmvi_Pctbf2 { get; set; }
        public decimal? Fcrmvi_Pctbf3 { get; set; }
        public decimal? Fcrmvi_Pctbf4 { get; set; }
        public decimal? Fcrmvi_Pctbf5 { get; set; }
        public decimal? Fcrmvi_Pctbf6 { get; set; }
        public decimal? Fcrmvi_Pctbf7 { get; set; }
        public decimal? Fcrmvi_Pctbf8 { get; set; }
        public decimal? Fcrmvi_Pctbf9 { get; set; }
        public decimal? Fcrmvi_Pctbfn { get; set; }
        public string Fcrmvi_Textos { get; set; }
        public decimal? Fcrmvi_Cntpen { get; set; }
        public string Fcrmvi_Empori { get; set; }
        public string Fcrmvi_Modori { get; set; }
        public string Fcrmvi_Codori { get; set; }
        public int? Fcrmvi_Nroori { get; set; }
        public int? Fcrmvi_Itmori { get; set; }
        public string Fcrmvi_Expori { get; set; }
        public decimal? Fcrmvi_Cntbon { get; set; }
        public string Fcrmvi_Cuenta { get; set; }
        public decimal? Fcrmvi_Cntant { get; set; }
        public decimal? Fcrmvi_Porant { get; set; }
        public string Fcrmvi_Artequ { get; set; }
        public decimal? Fcrmvi_Cantst { get; set; }
        public decimal? Fcrmvi_Cntori { get; set; }
        public string Fcrmvi_Mcdapl { get; set; }
        public string Fcrmvi_Ccdapl { get; set; }
        public string Fcrmvi_Deptra { get; set; }
        public string Fcrmvi_Sectra { get; set; }
        public string Fcrmvi_Empini { get; set; }
        public string Fcrmvi_Modini { get; set; }
        public string Fcrmvi_Codini { get; set; }
        public int? Fcrmvi_Nroini { get; set; }
        public int? Fcrmvi_Itmini { get; set; }
        public string Fcrmvi_Nivini { get; set; }
        public string Fcrmvi_Coflis { get; set; }
        public decimal? Fcrmvi_Cambio { get; set; }
        public string Fcrmvi_Empgan { get; set; }
        public string Fcrmvi_Modgan { get; set; }
        public string Fcrmvi_Codgan { get; set; }
        public int? Fcrmvi_Nrogan { get; set; }
        public decimal? Fcrmvi_Cntvar { get; set; }
        public decimal? Fcrmvi_Cntuni { get; set; }
        public decimal? Fcrmvi_Factor { get; set; }
        public string Fcrmvi_Ncnpna { get; set; }
        public string Fcrmvi_Ngenpn { get; set; }
        public string Fcrmvi_Ncanpn { get; set; }
        public string Fcrmvi_Ngenst { get; set; }
        public decimal? Fcrmvi_Presec { get; set; }
        public string Fcrmvi_Tipopr { get; set; }
        public string Fcrmvi_Codopr { get; set; }
        public decimal? Fcrmvi_Pctcom { get; set; }
        public string Fcrmvi_Modost { get; set; }
        public string Fcrmvi_Empost { get; set; }
        public string Fcrmvi_Codost { get; set; }
        public int? Fcrmvi_Nroost { get; set; }
        public int? Fcrmvi_Itmost { get; set; }
        public string Fcrmvi_Expost { get; set; }
        public decimal? Fcrmvi_Prenac { get; set; }
        public decimal? Fcrmvi_Preext { get; set; }
        public decimal? Fcrmvi_Preuss { get; set; }
        public decimal? Fcrmvi_Totlin { get; set; }
        public string Fcrmvi_Codpro { get; set; }
        public string Fcrmvi_Codtar { get; set; }
        public string Fcrmvi_Cancel { get; set; }
        public string Fcrmvi_Aerpue { get; set; }
        public string Usr_Fcrmvi_Dirent { get; set; }
        public string Usr_Fcrmvi_Diren2 { get; set; }
        public string Usr_Fcrmvi_Cndpag { get; set; }
        public string Usr_Fcrmvi_Vnddor { get; set; }
        public string Usr_Fcrmvi_Acopio { get; set; }
        public string Usr_Fcrmvi_Facant { get; set; }
        public string Usr_Fcrmvi_Trared { get; set; }
        public decimal? Usr_Fcrmvi_Totbon { get; set; }
        public decimal? Usr_Fcrmvi_Stdisp { get; set; }
        public int? Usr_Fcrmvi_Bultos { get; set; }
        public int? Usr_Fcrmvi_Palets { get; set; }
        public string Usr_Fcrmvi_Codzon { get; set; }
        public DateTime? Fcrmvi_Fecalt { get; set; }
        public DateTime? Fcrmvi_Fecmod { get; set; }
        public string Fcrmvi_Userid { get; set; }
        public string Fcrmvi_Ultopr { get; set; }
        public string Fcrmvi_Debaja { get; set; }
        public string Fcrmvi_Oalias { get; set; }

        public virtual Fcrmvh Pedido { get; set; }
    }
}
