using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace APISoftlandAnclaflex.Entities
{
    public partial class Fcrmvh
    {
        public string Fcrmvh_Codemp { get; set; }
        public string Fcrmvh_Modfor { get; set; }
        public string Fcrmvh_Codfor { get; set; }
        public int Fcrmvh_Nrofor { get; set; }
        public string Fcrmvh_Circom { get; set; }
        public string Fcrmvh_Cirapl { get; set; }
        public string Fcrmvh_Sucurs { get; set; }
        public DateTime Fcrmvh_Fchmov { get; set; }
        public string Fcrmvh_Nrocta { get; set; }
        public string Fcrmvh_Nrosub { get; set; }
        public string Fcrmvh_Mascar { get; set; }
        public string Fcrmvh_Dirent { get; set; }
        public string Fcrmvh_Paient { get; set; }
        public string Fcrmvh_Codent { get; set; }
        public string Fcrmvh_Camion { get; set; }
        public string Fcrmvh_Vnddor { get; set; }
        public string Fcrmvh_Cndpag { get; set; }
        public string Fcrmvh_Deposi { get; set; }
        public string Fcrmvh_Sector { get; set; }
        public string Fcrmvh_Codlis { get; set; }
        public DateTime? Fcrmvh_Feclis { get; set; }
        public string Fcrmvh_Congel { get; set; }
        public string Fcrmvh_Grubon { get; set; }
        public string Fcrmvh_Tracod { get; set; }
        public string Fcrmvh_Transp { get; set; }
        public string Fcrmvh_Tipdoc { get; set; }
        public string Fcrmvh_Trcuit { get; set; }
        public string Fcrmvh_Trandr { get; set; }
        public string Fcrmvh_Textos { get; set; }
        public string Fcrmvh_Empgen { get; set; }
        public string Fcrmvh_Modgen { get; set; }
        public string Fcrmvh_Codgen { get; set; }
        public string Fcrmvh_Modulo { get; set; }
        public string Fcrmvh_Coflis { get; set; }
        public string Fcrmvh_Coffac { get; set; }
        public string Fcrmvh_Cofdeu { get; set; }
        public decimal? Fcrmvh_Cambio { get; set; }
        public decimal? Fcrmvh_Camuss { get; set; }
        public string Fcrmvh_Cirgen { get; set; }
        public short? Fcrmvh_Impres { get; set; }
        public int Fcrmvh_Nrogen { get; set; }
        public string Fcrmvh_Imptcn { get; set; }
        public string Fcrmvh_Nombre { get; set; }
        public string Fcrmvh_Direcc { get; set; }
        public string Fcrmvh_Codpai { get; set; }
        public string Fcrmvh_Codpos { get; set; }
        public string Fcrmvh_Coniva { get; set; }
        public string Fcrmvh_Cntpdc { get; set; }
        public string Fcrmvh_Nrodoc { get; set; }
        public string Fcrmvh_Dimobl { get; set; }
        public string Fcrmvh_Subcue { get; set; }
        public string Fcrmvh_Dimori { get; set; }
        public string Fcrmvh_Subori { get; set; }
        public string Fcrmvh_Jurisd { get; set; }
        public string Fcrmvh_Deptra { get; set; }
        public string Fcrmvh_Sectra { get; set; }
        public string Fcrmvh_Empocj { get; set; }
        public string Fcrmvh_Modocj { get; set; }
        public string Fcrmvh_Codocj { get; set; }
        public int? Fcrmvh_Nroocj { get; set; }
        public string Fcrmvh_Empost { get; set; }
        public string Fcrmvh_Modost { get; set; }
        public string Fcrmvh_Codost { get; set; }
        public int? Fcrmvh_Nroost { get; set; }
        public string Fcrmvh_Cndiva { get; set; }
        public DateTime? Fcrmvh_Fchdes { get; set; }
        public DateTime? Fcrmvh_Fchhas { get; set; }
        public string Fcrmvh_Conbon { get; set; }
        public string Fcrmvh_Clprfa { get; set; }
        public short? Fcrmvh_Estaut { get; set; }
        public string Fcrmvh_Usraut { get; set; }
        public DateTime? Fcrmvh_Fchaut { get; set; }
        public string Fcrmvh_Oleole { get; set; }
        public string Fcrmvh_Bmpbmp { get; set; }
        public DateTime? Fcrmvh_Fchven { get; set; }
        public string Fcrmvh_Empfcr { get; set; }
        public string Fcrmvh_Modfcr { get; set; }
        public string Fcrmvh_Codfcr { get; set; }
        public int? Fcrmvh_Nrofcr { get; set; }
        public DateTime? Fcrmvh_Fecfcr { get; set; }
        public string Fcrmvh_Modfst { get; set; }
        public string Fcrmvh_Codfst { get; set; }
        public int? Fcrmvh_Nrofst { get; set; }
        public string Fcrmvh_Accfst { get; set; }
        public decimal? Fcrmvh_Camsec { get; set; }
        public string Fcrmvh_Tipopr { get; set; }
        public string Fcrmvh_Codopr { get; set; }
        public short? Fcrmvh_Diaent { get; set; }
        public string Fcrmvh_Horent { get; set; }
        public string Fcrmvh_Contac { get; set; }
        public string Fcrmvh_Telefn { get; set; }
        public string Fcrmvh_Codzon { get; set; }
        public string Fcrmvh_Municp { get; set; }
        public string Fcrmvh_Isprct { get; set; }
        public string Fcrmvh_Ctaen1 { get; set; }
        public string Fcrmvh_Cdent1 { get; set; }
        public string Fcrmvh_Ctaen2 { get; set; }
        public string Fcrmvh_Cdent2 { get; set; }
        public string Fcrmvh_Empfst { get; set; }
        public string Fcrmvh_Canant { get; set; }
        public string Fcrmvh_Comori { get; set; }
        public string Fcrmvh_Codori { get; set; }
        public string Fcrmvh_Jurctd { get; set; }
        public decimal? Fcrmvh_Pctdes { get; set; }
        public decimal? Fcrmvh_Pctfin { get; set; }
        public decimal? Fcrmvh_Tasain { get; set; }
        public decimal? Fcrmvh_Pctbf1 { get; set; }
        public decimal? Fcrmvh_Pctbf2 { get; set; }
        public decimal? Fcrmvh_Pctbf3 { get; set; }
        public decimal? Fcrmvh_Pctbf4 { get; set; }
        public decimal? Fcrmvh_Pctbf5 { get; set; }
        public decimal? Fcrmvh_Pctbl1 { get; set; }
        public decimal? Fcrmvh_Pctbl2 { get; set; }
        public decimal? Fcrmvh_Pctbl3 { get; set; }
        public short? Fcrmvh_Diadi1 { get; set; }
        public decimal? Fcrmvh_Pctdi1 { get; set; }
        public decimal? Fcrmvh_Pctdm1 { get; set; }
        public short? Fcrmvh_Diadi2 { get; set; }
        public decimal? Fcrmvh_Pctdi2 { get; set; }
        public decimal? Fcrmvh_Pctdm2 { get; set; }
        public short? Fcrmvh_Diadi3 { get; set; }
        public decimal? Fcrmvh_Pctdi3 { get; set; }
        public decimal? Fcrmvh_Pctdm3 { get; set; }
        public decimal? Fcrmvh_Dialib { get; set; }
        public string Fcrmvh_Edvacp { get; set; }
        public string Fcrmvh_Docfis { get; set; }
        public string Fcrmvh_Letfis { get; set; }
        public string Fcrmvh_Sucfis { get; set; }
        public int? Fcrmvh_Nrofis { get; set; }
        public string Fcrmvh_Cndcom { get; set; }
        public string Fcrmvh_Tipexp { get; set; }
        public string Fcrmvh_Nrocae { get; set; }
        public string Fcrmvh_Auxdev { get; set; }
        public string Fcrmvh_Motdev { get; set; }
        public string Fcrmvh_Embarq { get; set; }
        public string Fcrmvh_Aerpue { get; set; }
        public string Fcrmvh_Clasif { get; set; }
        public DateTime? Fcrmvh_Fecalt { get; set; }
        public DateTime? Fcrmvh_Fecmod { get; set; }
        public string Fcrmvh_Userid { get; set; }
        public string Fcrmvh_Ultopr { get; set; }
        public string Fcrmvh_Debaja { get; set; }
        public string Fcrmvh_Oalias { get; set; }
        public short? Usr_Fcrmvh_Estaut { get; set; }
        public string Usr_Fcrmvh_Retira { get; set; }
        public string Usr_Fcrmvh_Acopio { get; set; }
        public string Usr_Fcrmvh_Facant { get; set; }
        public int? Usr_Fcrmvh_Nrolem { get; set; }
        public string Usr_Fcrmvh_Trared { get; set; }
        public string Usr_Fcrmvh_Nrorem { get; set; }
        public string Usr_Fcrmvh_Muedon { get; set; }
        public string Usr_Fcrmvh_Consig { get; set; }
        public string Usr_Fcrmvh_Logist { get; set; }
        public short? Usr_Fcrmvh_Autcom { get; set; }
        public string Usr_Fcrmvh_Usrcom { get; set; }
        public DateTime? Usr_Fcrmvh_Fecaut { get; set; }
        public string Usr_Fcrmvh_Obscom { get; set; }
        public string Usr_Fcrmvh_Direml { get; set; }
        public int? Fcrmvh_Claaut { get; set; }
        public string Sar_Fcrmvh_Envmai { get; set; }
        public string Sar_Fcrmvh_Userml { get; set; }
        public string Sar_Fcrmvh_Nickml { get; set; }
        public string Sar_Fcrmvh_Tranum { get; set; }
        public string Sar_Fcrmvh_Traurl { get; set; }
    }
}
